### ISSUE TITLE
[FEATURE] Create token for error 'Permissions is not supported in your browser'

### ISSUE THREAD

**Issue by zy2ba** [ng-web-apis/permissions#4]
# 🚀 Feature request

### Is your feature request related to a problem?

I'll need to implements some special cases for not supported browsers and now must compare error with magic string for detect this situation

### Describe the solution you'd like

Create token for 'Permissions is not supported in your browser' error and export them for compare with really throwed error

**Comment by waterplea** [comment]
There is already a token for support, isn't it sufficient?
https://github.com/ng-web-apis/permissions#tokens

**Comment by zy2ba** [comment]
I've mean token for error message. At now lib throwing magic string if support check failed.
But, if I check permission availability first, I never get this error. Really, this closes my case. Thanks for the quick response
