### ISSUE TITLE
[FEATURE] Add attention to readme

### ISSUE THREAD

**Issue by zy2ba** [ng-web-apis/permissions#5]
# 🚀 Feature request

### Is your feature request related to a problem?

Even last  versions of safari does not support Permissions API. That may be trap for some newbie

### Describe the solution you'd like

Add attention text about need to check browser support near to MDN reference

**Comment by waterplea** [comment]
Good idea. I've added Browser support section:
https://github.com/ng-web-apis/permissions#browser-support
